// src/auth-screen.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ChatClient } from './chat-client';

@Component({
  selector: 'app-auth-screen',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="auth-container">
      <button class="back-button" (click)="back.emit()">← Back to servers</button>
      
      <div class="server-info">Connected to: {{serverUrl}}</div>
      
      <div class="card">
        <div class="header">
          <h2>{{isLogin ? 'Login' : 'Register'}}</h2>
          <p>{{isLogin ? 'Welcome back!' : 'Create your account'}}</p>
        </div>
        
        <div *ngIf="error" class="error">{{error}}</div>
        
        <div class="form-group">
          <label>Username</label>
          <input 
            type="text" 
            [(ngModel)]="username"
            placeholder="Enter your username"
            [disabled]="loading"
          >
        </div>
        
        <div class="form-group">
          <label>Password</label>
          <input 
            type="password" 
            [(ngModel)]="password"
            placeholder="Enter your password"
            [disabled]="loading"
          >
        </div>
        
        <button 
          (click)="authenticate()"
          [disabled]="!username.trim() || !password.trim() || loading"
        >
          {{loading ? '...' : (isLogin ? 'Login' : 'Register')}}
        </button>
        
        <button 
          class="secondary" 
          (click)="switchMode()"
          [disabled]="loading"
        >
          {{isLogin ? 'Need an account? Register' : 'Have an account? Login'}}
        </button>
      </div>
    </div>
  `,
  styles: [`
    .auth-container { max-width: 400px; margin: 40px auto; }
    .card { background: var(--card-bg, #fff); border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); padding: 32px; }
    .dark .card { --card-bg: #2d2d2d; }
    .header { text-align: center; margin-bottom: 32px; }
    .form-group { margin-bottom: 20px; }
    label { display: block; margin-bottom: 8px; font-weight: 500; color: var(--text-primary, #333); }
    input { width: 100%; padding: 12px; border: 1px solid #ddd; border-radius: 4px; font-size: 14px; box-sizing: border-box; background: var(--input-bg, #fff); color: var(--input-color, #333); }
    .dark input { --input-bg: #333; --input-color: #fff; border-color: #555; }
    button { background: #1976d2; color: white; border: none; border-radius: 4px; padding: 12px 24px; cursor: pointer; font-size: 14px; width: 100%; margin-bottom: 12px; }
    button:disabled { background: #ccc; cursor: not-allowed; }
    button.secondary { background: transparent; color: #1976d2; border: 1px solid #1976d2; }
    .error { background: #ffebee; color: #c62828; padding: 12px; border-radius: 4px; margin-bottom: 16px; border: 1px solid #ffcdd2; }
    .dark .error { background: #311b1b; color: #ef9a9a; border-color: #7b1f1f; }
    .back-button { background: none; border: none; color: #666; cursor: pointer; margin-bottom: 16px; padding: 8px 0; }
    .dark .back-button { color: #aaa; }
    .server-info { text-align: center; margin-bottom: 20px; padding: 12px; background: #e3f2fd; border-radius: 4px; font-size: 14px; }
    .dark .server-info { background: #1a3a5c; color: #90caf9; }
  `]
})
export class AuthScreenComponent {
  @Input() serverUrl = '';
  @Output() login = new EventEmitter<{token: string, username: string}>();
  @Output() back = new EventEmitter();

  username = '';
  password = '';
  isLogin = true;
  loading = false;
  error = '';

  async authenticate() {
    if (!this.username.trim() || !this.password.trim()) {
      this.error = 'Please enter username and password';
      return;
    }

    this.loading = true;
    this.error = '';

    try {
      const client = new ChatClient(this.serverUrl);
      const result = this.isLogin 
        ? await client.login(this.username, this.password)
        : await client.register(this.username, this.password);

      if (result.success) {
        client.setToken(result.token);
        this.login.emit({token: result.token, username: this.username});
      } else {
        this.error = result.error || 'Authentication failed';
      }
    } catch (error: any) {
      this.error = error.message || 'Authentication failed';
    } finally {
      this.loading = false;
    }
  }

  switchMode() {
    this.isLogin = !this.isLogin;
    this.error = '';
  }
}

// src/pages/AuthScreen.jsx
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonItem,
  IonInput,
  IonButton,
  IonLabel,
  IonCard,
  IonCardContent,
  IonText
} from '@ionic/react';
import { useState, memo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

function AuthScreen({ serverUrl, onLogin, onNavigate }) {
  const [isLogin, setIsLogin] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ username: '', password: '' });

  const handleAuth = async () => {
    if (!form.username || !form.password) {
      setError('Please enter username and password');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const ping = await fetch(`${serverUrl}/api/ping`);
      if (!ping.ok) {
        throw new Error('Server not responding');
      }

      const { ChatClient } = await import('dumb_api_js');
      const client = new ChatClient({ serverUrl });

      let result;
      
      if (isLogin) {
        result = await client.login(form.username, form.password);
      } else {
        result = await client.register(form.username, form.password);
        if (result.success) {
          result = await client.login(form.username, form.password);
        }
      }

      if (result.success && result.token) {
        onLogin(result.token, form.username);
      } else {
        setError(result.message || 'Authentication failed');
      }
      
    } catch (error) {
      setError(error.message || 'Connection failed');
    } finally {
      setLoading(false);
    }
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { 
      opacity: 1, 
      y: 0,
      transition: { duration: 0.5, ease: "easeOut" }
    }
  };

  const errorVariants = {
    hidden: { opacity: 0, height: 0 },
    visible: { 
      opacity: 1, 
      height: "auto",
      transition: { duration: 0.3 }
    }
  };

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar style={{ '--background': '#2d004d', '--color': 'white' }}>
          <IonTitle>{isLogin ? 'Login' : 'Register'}</IonTitle>
        </IonToolbar>
      </IonHeader>
      
      <IonContent>
        <div style={{ padding: '16px', maxWidth: '400px', margin: '0 auto' }}>
          <motion.div
            variants={cardVariants}
            initial="hidden"
            animate="visible"
            key={isLogin ? 'login' : 'register'}
          >
            <IonCard style={{ 
              '--background': 'var(--ion-color-light)',
              'border-radius': '16px',
              'box-shadow': '0 4px 20px rgba(45, 0, 77, 0.1)'
            }}>
              <IonCardContent>
                <h2 style={{ 
                  textAlign: 'center', 
                  marginBottom: '20px',
                  color: '#2d004d',
                  fontWeight: '600'
                }}>
                  {isLogin ? 'Welcome Back' : 'Create Account'}
                </h2>
                
                <IonItem style={{ 
                  '--border-radius': '12px',
                  '--padding-start': '0', 
                  '--inner-padding-end': '0',
                  '--background': 'transparent',
                  marginBottom: '16px'
                }}>
                  <IonLabel position="stacked" style={{ fontSize: '16px', marginBottom: '8px', fontWeight: '500' }}>Username</IonLabel>
                  <IonInput
                    value={form.username}
                    onIonInput={e => setForm(prev => ({ ...prev, username: e.detail.value }))}
                    placeholder="Enter username"
                    style={{ 
                      '--background': 'white',
                      '--color': 'var(--ion-color-dark)',
                      '--padding-start': '16px',
                      '--padding-end': '16px',
                      'border-radius': '12px',
                      'border': '1px solid var(--ion-color-medium)'
                    }}
                  />
                </IonItem>
                
                <IonItem style={{ 
                  '--border-radius': '12px',
                  '--padding-start': '0', 
                  '--inner-padding-end': '0',
                  '--background': 'transparent',
                  marginBottom: '24px'
                }}>
                  <IonLabel position="stacked" style={{ fontSize: '16px', marginBottom: '8px', fontWeight: '500' }}>Password</IonLabel>
                  <IonInput
                    type="password"
                    value={form.password}
                    onIonInput={e => setForm(prev => ({ ...prev, password: e.detail.value }))}
                    placeholder="Enter password"
                    style={{ 
                      '--background': 'white',
                      '--color': 'var(--ion-color-dark)',
                      '--padding-start': '16px',
                      '--padding-end': '16px',
                      'border-radius': '12px',
                      'border': '1px solid var(--ion-color-medium)'
                    }}
                  />
                </IonItem>
                
                <AnimatePresence>
                  {error && (
                    <motion.div
                      variants={errorVariants}
                      initial="hidden"
                      animate="visible"
                      exit="hidden"
                      style={{
                        background: 'rgba(244, 67, 54, 0.1)',
                        border: '1px solid rgba(244, 67, 54, 0.3)',
                        borderRadius: '8px',
                        padding: '12px',
                        marginBottom: '16px'
                      }}
                    >
                      <IonText color="danger" style={{ 
                        display: 'block', 
                        textAlign: 'center',
                        fontSize: '14px',
                        fontWeight: '500'
                      }}>
                        {error}
                      </IonText>
                    </motion.div>
                  )}
                </AnimatePresence>
                
                <IonButton
                  expand="block"
                  onClick={handleAuth}
                  disabled={loading}
                  style={{ 
                    marginTop: '16px',
                    '--border-radius': '12px',
                    '--background': '#2d004d',
                    '--background-activated': '#4a0072',
                    '--background-focused': '#4a0072',
                    height: '48px',
                    fontSize: '16px',
                    fontWeight: '600'
                  }}
                >
                  {loading ? 'Please wait...' : (isLogin ? 'Login' : 'Register')}
                </IonButton>
                
                <IonButton
                  expand="block"
                  fill="clear"
                  onClick={() => {
                    setIsLogin(!isLogin);
                    setError('');
                    setForm({ username: '', password: '' });
                  }}
                  disabled={loading}
                  style={{ 
                    marginTop: '8px',
                    '--color': '#2d004d',
                    fontSize: '14px'
                  }}
                >
                  {isLogin ? 'Need an account? Register' : 'Have an account? Login'}
                </IonButton>
              </IonCardContent>
            </IonCard>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            style={{ textAlign: 'center', marginTop: '20px' }}
          >
            <IonButton 
              fill="outline" 
              onClick={() => onNavigate('server')}
              style={{
                '--border-color': '#2d004d',
                '--color': '#2d004d',
                '--border-radius': '12px'
              }}
            >
              Back to Server Selection
            </IonButton>
          </motion.div>
        </div>
      </IonContent>
    </IonPage>
  );
}

export default memo(AuthScreen);
